### ISSUE TITLE
Lista de Swags a serem criados

### ISSUE THREAD

**Issue by luiguild** [RioMozillaClub/swag-list#1]
Adesivos - 1000
Bottons - (Quantidade indefinida)
Camisetas - 100
Canetas - 100
Casacos - 30
Canecas - 108
Cadernos - 100
Bolsas Boxer - 100
Pendrive - 100

Caso exista mais alguma ideia, é só sinalizar :P

**Comment by luiguild** [comment]
Encontrei uma série de casacos maneiríssimos. Nossa ideia era replicar exatamente aquele do FISL. Eu o encontrei, porém está indisponível na web, parece que saiu de linha =(

A ideia do layout é bordar nas costas grande o nome do club e talvez no peito também pequeno
http://www.decathlon.com.br/montanha---aventura/aventura-homem/roupas-de-frio---camada-2/casaco-fleece-masculina-forcla_39634?skuId=1551263

Encontrei alguns outros que aparentemente são tão bons quanto.
Esse é o meu favorito
http://www.netshoes.com.br/produto/agasalho-gonew-college-C62-0363-852?

http://www.decathlon.com.br/esporte-aquaticos/roupas-de-barco/jaquetas-masculinas/casaco-raincoastal-homem_43994?skuId=604569

http://www.decathlon.com.br/montanha---aventura/aventura-homem/roupas-de-frio---camada-2/casaco-fleece-masculina-forcla_39634?skuId=1551377

http://www.decathlon.com.br/montanha---aventura/aventura-homem/impermeaveis---camada-3/jaqueta-impermeavel-raincut_212575?skuId=1803675

http://www.netshoes.com.br/produto/agasalho-puma-fun-cb-tricot-D14-0158-118?

http://www.netshoes.com.br/produto/blusao-joma-champion-049-3042-543?

http://www.netshoes.com.br/produto/jaqueta-umbro-classics-c-capuz-D21-0157-066?

http://www.netshoes.com.br/produto/jaqueta-gonew-college-C62-0372-852?photo=selected_photo1
(essa é ótima, mas me explica o porque desta merda de número nas costas)

http://www.netshoes.com.br/produto/moletom-puma-ess-hooded-sweat-tr-c-capuz-D14-0982-162?
(esse é excelente, porém é um moletom)

**Comment by luiguild** [comment]
No lugar da bolsa boxer, encontrei essa bolsa aqui. Por mim já está decidido. Nunca encontraremos uma outra mochila na mesma qualidade dessa, no mesmo preço.

http://produto.mercadolivre.com.br/MLB-697745318-mochila-arpenaz-10-quechua-_JM
Está no mercado livre, mas o vendedor é da Decathlon. A mochila é da mesma marca daquela jaqueta do FISL.

**Comment by Raphseck** [comment]
Casaco gostei desse:
http://www.netshoes.com.br/produto/agasalho-gonew-college-C62-0363-852?

Gostei da ideia da mochila.
Só não gostei muita da marca ali em baixo.

**Comment by luiguild** [comment]
Em construção...

Base de cotação R$3,8 = $1

Adesivos 1000 = 
Camisetas R$1un / $1un -> 120(70 Masculinas / 50 Femininas) =
Canecas R$14un / $3,68un -> 108 = R$1512 / $397
Bolsas Boxer R$16,90un / $4,44un -> 100 = R$1690 / $444
Mochila R$29,90un / $7,86un -> 30 = R$897 / $236
