### ISSUE TITLE
Layouts de Swag a serem criados

### ISSUE THREAD

**Issue by luiguild** [RioMozillaClub/swag-list#2]
Camisetas
- A ideia inicial propõe uma camiseta azul no tom da marca e as escritas em branco

Adesivos
- Adesivos com recorte eletrônico levando em consideração a ideia dos badges. O tamanho terá a média de 7cm X 7cm

Bottons
- Continuar a ideia dos badges em dois tamanhos

Canecas
- Bolar layout, ideias são aceitas :P

Bolsas Boxer
- Bolar layout, ideias são aceitas :P

Pendrive
- Bolar layout, ideias são aceitas :P

**Comment by luiguild** [comment]
@Raphseck o adesivo será só o logo dos clubs com recorte eletrônico mesmo. A borda do recorte é branca e de 5mm :D

**Comment by Raphseck** [comment]
Prévia do adesivo:
![adesivo-01](https://cloud.githubusercontent.com/assets/14264676/13301379/5a1d5a70-db23-11e5-951b-bee46ca48e05.jpg)
